# Generated by Django 5.1.1 on 2024-09-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0002_alter_file_id_alter_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='data_type',
            field=models.CharField(choices=[('folder', 'Folder'), ('file', 'File')], default='file', max_length=20),
        ),
        migrations.AddField(
            model_name='folder',
            name='data_type',
            field=models.CharField(choices=[('folder', 'Folder'), ('file', 'File')], default='folder', max_length=20),
        ),
    ]
