# Generated by Django 5.1.1 on 2024-09-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0003_file_data_type_folder_data_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='id',
            new_name='data_id',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='id',
            new_name='data_id',
        ),
    ]
