# Generated by Django 5.1.1 on 2024-09-25 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0005_file_created_at_file_shared_with_file_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='shared_with',
        ),
        migrations.CreateModel(
            name='UserFilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('owner', 'Owner')], max_length=10)),
                ('shared_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagine.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'file')},
            },
        ),
        migrations.AddField(
            model_name='file',
            name='shared_with_file',
            field=models.ManyToManyField(blank=True, related_name='shared_files', through='imagine.UserFilePermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserFolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('owner', 'Owner')], max_length=10)),
                ('shared_on', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagine.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'folder')},
            },
        ),
        migrations.AddField(
            model_name='folder',
            name='shared_with_folder',
            field=models.ManyToManyField(blank=True, related_name='shared_folders', through='imagine.UserFolderPermission', to=settings.AUTH_USER_MODEL),
        ),
    ]
