# Generated by Django 5.1.1 on 2024-09-29 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0006_remove_file_shared_with_userfilepermission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trasher',
            fields=[
                ('t_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('dlt_at', models.DateTimeField(auto_now=True)),
                ('prt_id', models.UUIDField(editable=False, unique=True)),
                ('dlt_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
