# Generated by Django 5.1.1 on 2024-09-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0007_trasher'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasher',
            name='path_list',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
