# Generated by Django 5.1.1 on 2024-09-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0008_trasher_path_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasher',
            name='data_type',
            field=models.CharField(choices=[('folder', 'Folder'), ('file', 'File')], default='folder', max_length=20),
        ),
    ]
