# Generated by Django 5.1.1 on 2024-09-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0009_trasher_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasher',
            name='prt_id',
            field=models.UUIDField(editable=False),
        ),
    ]
