# Generated by Django 5.1.1 on 2024-11-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagine', '0010_alter_trasher_prt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_deleted',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_deleted',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=20),
        ),
    ]
